# @package _group_
_target_: diarizen_pyannote.audio.models.segmentation.SSeRiouSS
wav2vec: WAVLM_BASE
wav2vec_layer: -1
lstm:
  hidden_size: 128
  num_layers: 4
  bidirectional: true
  monolithic: true
  dropout: 0.5
linear:
  hidden_size: 128
  num_layers: 2
